### ISSUE TITLE
iSCSI volumes become read-only after some time.

### ISSUE THREAD

**Issue by theadzik** [SynologyOpenSource/synology-csi#101]
After running correctly for some time one of my volumes becomes read-only. If I move all of my workloads to a new node it is mounted again as read-write, but then it crashes again after some time.

I'm not sure what happens that makes my volumes become read only.

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-retain
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.san.synology.com
parameters:
  fsType: 'btrfs'
  formatOptions: '--nodiscard'
reclaimPolicy: Retain
allowVolumeExpansion: true
```

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Ti
  storageClassName: synology-iscsi-retain
```

This volume is used by multiple pods (6). No other volume becomes read-only, but this is the only one shared.

Some info from the node:

```bash
$ mount | grep -i ba42fc21
/dev/sdb on /var/lib/kubelet/pods/16daf7d7-dd78-4634-9837-984525860b98/volumes/kubernetes.io~csi/pvc-ba42fc21-0f68-4ad6-bb1b-aa5c58b4c1eb/mount type btrfs (ro,relatime,discard=async,space_cache=v2,subvolid=5,subvol=/)
/dev/sdb on /var/lib/kubelet/pods/6e2f1251-6290-40f2-9ae1-8a9053058fb6/volumes/kubernetes.io~csi/pvc-ba42fc21-0f68-4ad6-bb1b-aa5c58b4c1eb/mount type btrfs (ro,relatime,discard=async,space_cache=v2,subvolid=5,subvol=/)
/dev/sdb on /var/lib/kubelet/pods/2bb65214-c86e-4c86-9ba0-ca54cdda395d/volumes/kubernetes.io~csi/pvc-ba42fc21-0f68-4ad6-bb1b-aa5c58b4c1eb/mount type btrfs (ro,relatime,discard=async,space_cache=v2,subvolid=5,subvol=/)
/dev/sdb on /var/lib/kubelet/pods/c1957f47-8c28-4e22-a65f-870e9ef6eeec/volumes/kubernetes.io~csi/pvc-ba42fc21-0f68-4ad6-bb1b-aa5c58b4c1eb/mount type btrfs (ro,relatime,discard=async,space_cache=v2,subvolid=5,subvol=/)
/dev/sdb on /var/lib/kubelet/pods/ffc4f6c8-203f-4d30-97ed-854c174e6db4/volumes/kubernetes.io~csi/pvc-ba42fc21-0f68-4ad6-bb1b-aa5c58b4c1eb/mount type btrfs (ro,relatime,discard=async,space_cache=v2,subvolid=5,subvol=/)
/dev/sdb on /var/lib/kubelet/pods/8daefc06-aef2-485d-b002-bbdb39ddee2d/volumes/kubernetes.io~csi/pvc-ba42fc21-0f68-4ad6-bb1b-aa5c58b4c1eb/mount type btrfs (ro,relatime,discard=async,space_cache=v2,subvolid=5,subvol=/)
```

```bash
$ iscsiadm -m session -P 3
iSCSI Transport Class version 2.0-870
version 2.1.8
Target: iqn.2000-01.com.synology:nas-1.pvc-ba42fc21-0f68-4ad6-bb1b-aa5c58b4c1eb (non-flash)
	Current Portal: 192.168.0.6:3260,1
	Persistent Portal: 192.168.0.6:3260,1
		**********
		Interface:
		**********
		Iface Name: default
		Iface Transport: tcp
		Iface Initiatorname: iqn.1993-08.org.debian:01:b59d4adebfa2
		Iface IPaddress: 192.168.0.3
		Iface HWaddress: default
		Iface Netdev: default
		SID: 73
		iSCSI Connection State: LOGGED IN
		iSCSI Session State: LOGGED_IN
		Internal iscsid Session State: NO CHANGE
		*********
		Timeouts:
		*********
		Recovery Timeout: 120
		Target Reset Timeout: 30
		LUN Reset Timeout: 30
		Abort Timeout: 15
		*****
		CHAP:
		*****
		username: <empty>
		password: ********
		username_in: <empty>
		password_in: ********
		************************
		Negotiated iSCSI params:
		************************
		HeaderDigest: None
		DataDigest: None
		MaxRecvDataSegmentLength: 262144
		MaxXmitDataSegmentLength: 262144
		FirstBurstLength: 65536
		MaxBurstLength: 262144
		ImmediateData: Yes
		InitialR2T: Yes
		MaxOutstandingR2T: 1
		************************
		Attached SCSI devices:
		************************
		Host Number: 3	State: running
		scsi3 Channel 00 Id 0 Lun: 1
			Attached scsi disk sdb		State: running
```
