### ISSUE TITLE
Couldn't find any host available to create Volume

### ISSUE THREAD

**Issue by smejkal** [SynologyOpenSource/synology-csi#65]
After spending many hours trying to solve the problem myself, I need help please...

I'm already using multiple LUNs (9 targets and 9 LUNs) on the DS918+ with my Kubernetes cluster, but by iscsi pv, not with the Synology CSI.

Versions:

```
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2
Synology CSI: latest
```

client-info.yml
```
clients:
  - host: 192.168.2.224
    port: 5000
    https: false
    username: user
    password: password`
```

storageclass:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-storage
  annotations:
    storage-class.kubernetes.io/is-default-class: "false"
provisioner: csi.san.synology.com
parameters:
  dsm: '192.168.2.224'
  location: '/volume1'
  fsType: 'btrfs'
  formatOptions: '--nodiscard'
  type: thin
reclaimPolicy: Retain
allowVolumeExpansion: true`
```

claim:

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
  namespace: synology-csi
  labels:
    app:
      test
spec:
  storageClassName: synology-iscsi-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
```

job:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: write
  namespace: test
spec:
  template:
    metadata:
      name: write
    spec:
      containers:
        - name: write
          image: registry.access.redhat.com/ubi8/ubi-minimal:latest
          command: ["dd","if=/dev/zero","of=/mnt/pv/test.img","bs=1G","count=1","oflag=dsync"]
          volumeMounts:
            - mountPath: "/mnt/pv"
              name: test-volume
      volumes:
        - name: test-volume
          persistentVolumeClaim:
            claimName: test-storage-claim
      restartPolicy: Never
```

Controller log:

```
controller.go:1279] provision "test/test-claim" class "synology-iscsi-storage": started
connection.go:183] GRPC call: /csi.v1.Controller/CreateVolume
event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"test", Name:"test-claim", UID:"3024a15d-4557-4c40-ba86-e0ebdf7d1ac9", APIVersion:"v1", ResourceVersion:"30936475", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "test/test-claim"
connection.go:184] GRPC request: {"capacity_range":{"required_bytes":4294967296},"name":"pvc-3024a15d-4557-4c40-ba86-e0ebdf7d1ac9","parameters":{"dsm":"192.168.2.224","formatOptions":"--nodiscard","fsType":"btrfs","location":"/volume1"},"volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"btrfs"}},"access_mode":{"mode":1}}]}
controller.go:956] error syncing claim "3024a15d-4557-4c40-ba86-e0ebdf7d1ac9": failed to provision volume with StorageClass "synology-iscsi-storage": rpc error: code = Internal desc = Couldn't find any host available to create Volume
```

What does 'couldn't find any host... " mean? Not find any DSM? Not find any node?

I read all the log files 1000 times...  No more ideas to resolve the issue. Not to see the forest anymore... Please help ;-)

**Comment by smejkal** [comment]
Unbelievable, I tried the same with my old ds216j and it works.

The procedure was exactly the same, just created a new user with admin rights and entered it in the client_info.yml. The only difference is the file system. With the ds2176 I now used ext4 and no brtfs. But I had already tested this with ext4 on the DS918 without success.

What else could be the reason? Any higher security settings? The firewall is disabled on both. 

And different are the existing manual created luns on the 918+. Could that be the problem?

**Comment by smejkal** [comment]
The system is screwing me over.

After I changed the storage class back to the ds918+, it worked there too.

The only difference now is that the client_info.yml contains 2 entries. The template also had 2 entries. Does this mean that it only works if there are 2 entries? Please not really...

**Comment by aSauerwein** [comment]
it's working for me with only 1 client configured. 
I had the same error message and my fault was that the user must have 2FA disabled and must be in administrators group

**Comment by plaurin84** [comment]
I am encountering the exact same issue.
I am not using any parameters in the storage class to keep the defaults.

My user has admin rights and 2FA is disabled also.

**Comment by plaurin84** [comment]
I am doing more tests... I believe I might have found the issue. But still trying to replicate the issue properly before sharing some more details.

I suspect there is a problem with too complex passwords in the secret. Maybe some special characters are not sent properly for authentication with DSM. Can't confirm for now.

**Comment by smejkal** [comment]
That surprises me very much. I have uninstalled and reinstalled the drivers several times. And so the pods were recreated too. Only after changing to another DS and back again did it work. But I can't explain why either.

I'm very excited about your findings.

**Comment by plaurin84** [comment]
Well... I am disappointed. It always work and I cannot reproduce the issue anymore. This is really strange.
I even deployed from a fresh Kubernetes cluster and still works out of the box without issue now.
¯\_(ツ)_/¯

**Comment by dcharbonnier** [comment]
I have the same issue, and this exact same setup was working, I only reinstalled the k8s, the manifests are the same, on the same machine with the same network.

**Comment by plaurin84** [comment]
The synology NAS I have been working on is not mine. I can't do much more at this point.

To help reproduce the issue, someone who owns a NAS and encountered the issue should probably try and factory-reset the NAS to see if it's possible to encounter the issue again. (Of course, if you don't have any data on it or you are okay with losing everything).

I hope to get one sometimes next year, I could try to figure this out again if not resolved.

**Comment by software-testing-professional** [comment]
Hi guys. 
I also struggled with these `Couldn't find any host available to create Volume` issues on my DS923+.
After lots of try and error, I added the CSI user to the 'Administrators' group in my Synology NAS. 
Since then the provisioning of volumes does work. 

So the `Couldn't find any host available to create Volume` message seems to be related to insufficient user rights on the Synology NAS. The error message is misleading and did cost me some hours...

I did not test different filesystems in this scenario, btw.

**Comment by bplein** [comment]
I struggled with this today. 

Then I noticed that the example `client-info.yaml` in the README.md is like this:
```
clients:
- host: 192.168.1.1
  port: 5000
  https: false
  username: <username>
  password: <password>
- host: 192.168.1.2
  port: 5001
  https: true
  username: <username>
  password: <password>
```
While the template file has the individual hosts outdented as this:
```
clients:
- host: 192.168.1.1
  port: 5000
  https: false
  username: <username>
  password: <password>
- host: 192.168.1.2
  port: 5001
  https: true
  username: <username>
  password: <password>
```

I don't know if they are equivalent YAML but I got it going with using the first example from the README.  When I tried to embed the information into the storageclass, it never did seem to work for me.
