### ISSUE TITLE
Failed to set NFS privilege rule

### ISSUE THREAD

**Issue by fish0373** [SynologyOpenSource/synology-csi#91]
I'm using NFS

This is my setting, it can create pv, but when pvc is bound, then I get this message.
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: csi.san.synology.com
parameters:
  dsm: 172.24.1.101
  location: /volume2
  mountPermissions: '0755'
  protocol: nfs
reclaimPolicy: Delete
mountOptions:
  - nfsvers=4.1
volumeBindingMode: Immediate
```

![image](https://github.com/user-attachments/assets/7b413c63-5f5c-4f7e-8115-d36eaf7ae1f8)
